eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8081
spring:
  application:
    name: server-feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html

  redis:
    host: localhost
    port: 6379
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
    timeout: 1000

  data:
    solr:
      host: http://localhost:8010/solr
feign:
  httpclient:
    enabled: true
