eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8081
spring:
  application:
    name: server-feign
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
feign:
  hystrix:
    enabled: true