eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8091
spring:
  application:
    name: service-feign
    thymeleaf.encoding: UTF-8
    thymeleaf.servlet.content-type: text/html
  redis:
    host: localhost
    port: 6379
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
    timeout: 1000
